config/routes.rb
Rails.application.routes.draw do
  resources :festivals do
    resources :musicians
  end
  resources :payment_methods
  resources :sales_reports
  resources :vendors
  resources :ticket_categories
  resources :instructions
  resources :assignments
  resources :tasks
  resources :task_types
  resources :instruments
  resources :team_musicians
  resources :accomodations
  resources :addresses
  devise_for :users
  resources :discussions
  resources :flights
  resources :airlines
  resources :sheets
  resources :notebooks
  resources :event_teams
  resources :events
  resources :teams
  resources :locations
  resources :types
  resources :pieces
  resources :performers
  resources :performances
  resources :musicians
  resources :movements
  resources :concerts
  resources :composers
  root to: 'events#index'
end

app/models/accomodation.rb
class Accomodation < ApplicationRecord
  belongs_to :address
  belongs_to :musician
  belongs_to :festival
end

app/controllers/accomodations_controller.rb
class AccomodationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_accomodation, only: [:show, :edit, :update, :destroy]

  # GET /accomodations
  # GET /accomodations.json
  def index
    @accomodations = Accomodation.where(festival_id: [nil, 5, 3])
  end

  # GET /accomodations/1
  # GET /accomodations/1.json
  def show
  end

  # GET /accomodations/new
  def new
    @accomodation = Accomodation.new
    @accomodation.arrival = "2021-08-15 16:00"
    @accomodation.departure = "2021-08-29 12:00"
    @accomodation.festival_id = 5
  end

  # GET /accomodations/1/edit
  def edit
  end

  # POST /accomodations
  # POST /accomodations.json
  def create
    @accomodation = Accomodation.new(accomodation_params)

    respond_to do |format|
      if @accomodation.save
        format.html { redirect_to @accomodation, notice: 'Accomodation was successfully created.' }
        format.json { render :show, status: :created, location: @accomodation }
      else
        format.html { render :new }
        format.json { render json: @accomodation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accomodations/1
  # PATCH/PUT /accomodations/1.json
  def update
    respond_to do |format|
      if @accomodation.update(accomodation_params)
        format.html { redirect_to @accomodation, notice: 'Accomodation was successfully updated.' }
        format.json { render :show, status: :ok, location: @accomodation }
      else
        format.html { render :edit }
        format.json { render json: @accomodation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accomodations/1
  # DELETE /accomodations/1.json
  def destroy
    @accomodation.destroy
    respond_to do |format|
      format.html { redirect_to accomodations_url, notice: 'Accomodation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accomodation
      @accomodation = Accomodation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accomodation_params
      params.require(:accomodation).permit(:address_id, :musician_id, :arrival, :departure, :co, :festival_id)
    end
end

app/helpers/accomodations_helper.rb
module AccomodationsHelper
end

app/views/accomodations/_accomodation_index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <% if user_signed_in? %> <th>Musician</th> <% end %>
      <th>Host</th>
      <th>Arrival</th>
      <th>Departure</th>
      <th>Co#</th>
      <% if user_signed_in? %> <th colspan="2"></th> <% end %>
    </tr>
  </thead>

  <tbody>
    <!% @accomodations.includes(:musician).order(arrival: :asc, 'LOWER(musicians.last)', "musicians.first").each do |accomodation| %>
    <% @accomodations.order(arrival: :asc).each do |accomodation| %>
      <tr>
        <% if user_signed_in? %> <td><%= accomodation.musician.name %></td> <% end %>
        <td><%= accomodation.address.nickname %></td>
        <td><%= accomodation.try(:arrival).try(:strftime, "%a %b %e") %></td>
        <td><%= accomodation.try(:departure).try(:strftime, "%a %b %e") %></td>
        <td><%= accomodation.co %></td>
        <% if user_signed_in? %>
	  <td><%= link_to 'Show', accomodation, class: 'btn btn-warning btn-sm' %></td>
          <td><%= link_to 'Edit', edit_accomodation_path(accomodation), class: 'btn btn-warning btn-sm' %></td>
          <td><%= link_to 'Destroy', accomodation, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

  <%= link_to 'New Accomodation', new_accomodation_path, class: 'btn btn-primary btn-sm'  %>

<br> <br> <br>

app/views/accomodations/_checkin_index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <% if user_signed_in? %> <th>Musician</th> <% end %>
      <th>Host</th>
      <th>Arrival</th>
      <th>Departure</th>
      <th>Notes</th>
      <% if user_signed_in? %> <th colspan="2"></th> <% end %>
    </tr>
  </thead>

  <% cdate = "" %>
  <% inProcess = false %>
  <% disp = "none" %>
  <% @accomodations.order(arrival: :asc).each do |accomodation| %>
    <% edate = accomodation.try(:arrival).try(:strftime, "%Y%m%d") %>
    <% if cdate == edate %>
	<% # if the dates match, do nothing %>
    <% else %>
      <% if inProcess == true %>
        <% # if we are already in a tbody, then close it out. %>
        </tbody>
        <% disp = "none" %>
      <% end %>
      <% cdate = edate %>
      <% inProcess = true %>
      <tbody id="<%="A" + cdate%>" style="display:<%=disp%>">
    <% end %>

      <tr>
        <% if user_signed_in? %> <td><%= accomodation.musician.name %></td> <% end %>
        <td><%= accomodation.address.nickname %></td>
        <td><%= accomodation.try(:arrival).try(:strftime, "%a %b %e") %></td>
        <td><%= accomodation.try(:departure).try(:strftime, "%a %b %e") %></td>
        <td><%= accomodation.co %></td>
        <% if user_signed_in? %>
	  <td><%= link_to 'Show', accomodation, class: 'btn btn-warning btn-sm' %></td>
          <td><%= link_to 'Edit', edit_accomodation_path(accomodation), 
	    class: 'btn btn-warning btn-sm' %></td>
          <td><%= link_to 'Destroy', accomodation, method: :delete,
	    data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Housing', new_accomodation_path, class: 'btn btn-primary btn-sm'  %>

<br> <br> <br>

app/views/accomodations/_checkout_index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <% if user_signed_in? %> <th>Musician</th> <% end %>
      <th>Host</th>
      <th>Arrival</th>
      <th>Departure</th>
      <th>Notes</th>
      <% if user_signed_in? %> <th colspan="2"></th> <% end %>
    </tr>
  </thead>

  <% cdate = "" %>
  <% inProcess = false %>
  <% disp = "none" %>
  <% @accomodations.order(departure: :asc).each do |accomodation| %>
    <% edate = accomodation.try(:departure).try(:strftime, "%Y%m%d") %>
    <% if cdate == edate %>
	<% # if the dates match, do nothing %>
    <% else %>
      <% if inProcess == true %>
        <% # if we are already in a tbody, then close it out. %>
        </tbody>
        <% disp = "none" %>
      <% end %>
      <% cdate = edate %>
      <% inProcess = true %>
      <tbody id="<%="B" + cdate%>" style="display:<%=disp%>">
    <% end %>

      <tr>
        <% if user_signed_in? %> <td><%= accomodation.musician.name %></td> <% end %>
        <td><%= accomodation.address.nickname %></td>
        <td><%= accomodation.try(:arrival).try(:strftime, "%a %b %e") %></td>
        <td><%= accomodation.try(:departure).try(:strftime, "%a %b %e") %></td>
        <td><%= accomodation.co %></td>
        <% if user_signed_in? %>
	  <td><%= link_to 'Show', accomodation, class: 'btn btn-warning btn-sm' %></td>
          <td><%= link_to 'Edit', edit_accomodation_path(accomodation), 
	    class: 'btn btn-warning btn-sm' %></td>
          <td><%= link_to 'Destroy', accomodation, method: :delete,
	    data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br> <br> <br>

app/views/accomodations/_form.html.erb
<%= simple_form_for(@accomodation) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :address, label_method: :nickname, collection: Address.order(:nickname) %>
    <%= f.association :musician, collection: Musician.order(:name) %>
    <%= f.input :arrival %>
    <%= f.input :departure %>
    <%= f.input :co %>
    <%= f.association :festival %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/accomodations/edit.html.erb
<h1>Editing Accommodation</h1>

<%= render 'form', accomodation: @accomodation %>

<br>

<%= link_to 'Show', @accomodation, class: "btn btn-warning btn-sm" %> |
<%= link_to 'Back', accomodations_path, class: "btn btn-warning btn-sm" %>

app/views/accomodations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accommodations</h1>

<%= render 'accomodation_index' %>

app/views/accomodations/new.html.erb
<h1>New Accommodation</h1>

<%= render 'form', accomodation: @accomodation %>

<br>

<%= link_to 'Back', accomodations_path, class: "btn btn-warning btn-sm" %>

app/views/accomodations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @accomodation.address.nickname %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @accomodation.arrival %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @accomodation.departure %>
</p>

<p>
  <strong>Co:</strong>
  <%= @accomodation.co %>
</p>

<p>
  <strong>Festival:</strong>
  <%= @accomodation.festival.name if @accomodation.festival %>
</p>

<br>

<%= link_to 'Edit', edit_accomodation_path(@accomodation), class: "btn btn-warning btn-sm" %> |
<%= link_to 'Back', accomodations_path, class: "btn btn-warning btn-sm" %>