config/routes.rb
Rails.application.routes.draw do
  resources :festivals do
    resources :musicians
  end
  resources :payment_methods
  resources :sales_reports
  resources :vendors
  resources :ticket_categories
  resources :instructions
  resources :assignments
  resources :tasks
  resources :task_types
  resources :instruments
  resources :team_musicians
  resources :accomodations
  resources :addresses
  devise_for :users
  resources :discussions
  resources :flights
  resources :airlines
  resources :sheets
  resources :notebooks
  resources :event_teams
  resources :events
  resources :teams
  resources :locations
  resources :types
  resources :pieces
  resources :performers
  resources :performances
  resources :musicians
  resources :movements
  resources :concerts
  resources :composers
  root to: 'events#index'
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  has_many :sheets, as: :pad, dependent: :destroy

  accepts_nested_attributes_for :sheets, allow_destroy: true,
    reject_if: ->(attrs) { attrs['note'].blank? }
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
    @discussion.date = Time.now.strftime("%d/%m/%Y")
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:date, :color, :resolved, sheets_attributes: [:id, :_destroy, :note] )
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= simple_form_for(@discussion) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date, as: :date, start_month: "August" %>
    <%= f.input :color %>
    <%= f.input :resolved %>
  </div>

  <div>
    <p><strong>Discussion:</strong></p>
 
    <div id="sheets">
      <%= f.fields_for :sheets do |sheet| %>
        <%= render '/sheets/sheet_fields', f: sheet %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'add note', f, :sheets, class: 'btn btn-success btn-sm' %>
      </div>
    </div>
  </div>

  <br>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/discussions/_sheet_fields.html.erb
<div class="nested-fields">
  <%= f.label :note %>
  <%= f.text_area :note %>

  <%= f.check_box :_destroy %>

  <%= link_to_remove_association "remove note", f, class: 'btn btn-danger btn-sm' %>
</div>

app/views/discussions/edit.html.erb
<h1>Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

<br>

<%= link_to 'Show', @discussion, class: 'btn btn-warning btn-sm' %> |
<%= link_to 'Back', discussions_path, class: 'btn btn-warning btn-sm' %>

app/views/discussions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discussions</h1>

<% @allOn = true %>
<%= render 'events/discussion_index' %>

<br>

<!-- the link is part of events/discussion_index so it's not necessary here  -->
<!-- = link_to 'New Discussion', new_discussion_path, class: 'btn btn-primary btn-sm' %>  -->

<br> <br> <br>

app/views/discussions/new.html.erb
<h1>New Discussion</h1>

<%= render 'form', discussion: @discussion %>

<br> 

<%= link_to 'Back', discussions_path, class: 'btn btn-warning btn-sm' %>

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @discussion.date.strftime("%a %m/%d/%y") %>
</p>

<p>
  <strong>Color:</strong>
  <%= @discussion.color %>
</p>

<p>
  <strong>Resolved:</strong>
  <%= @discussion.resolved %>
</p>

<h2>Nested Notes for <%= @discussion.date.strftime("%a %m/%d/%y") %> </h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Nested Notes </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bits = @discussion.sheets %>
    <% @bits.each do |s| %>
      <tr bgcolor="<%=@discussion.color%>">
        <td><%= s.created_at.strftime("%m/%d/%y %I:%M%p") %></td>
        <td colspan="2" ><%= s.note %></td>
        <td colspan="3" ></td>
        <td><%= link_to 'Edit', edit_sheet_path(s), class: 'btn btn-warning btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> 

<%= link_to 'Edit', edit_discussion_path(@discussion), class: 'btn btn-warning btn-sm' %> |
<%= link_to 'Back', discussions_path, class: 'btn btn-warning btn-sm' %>