config/routes.rb
Rails.application.routes.draw do
  resources :festivals do
    resources :musicians
  end
  resources :payment_methods
  resources :sales_reports
  resources :vendors
  resources :ticket_categories
  resources :instructions
  resources :assignments
  resources :tasks
  resources :task_types
  resources :instruments
  resources :team_musicians
  resources :accomodations
  resources :addresses
  devise_for :users
  resources :discussions
  resources :flights
  resources :airlines
  resources :sheets
  resources :notebooks
  resources :event_teams
  resources :events
  resources :teams
  resources :locations
  resources :types
  resources :pieces
  resources :performers
  resources :performances
  resources :musicians
  resources :movements
  resources :concerts
  resources :composers
  root to: 'events#index'
end

app/controllers/task_types_controller.rb
class TaskTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task_type, only: [:show, :edit, :update, :destroy]

  # GET /task_types
  # GET /task_types.json
  def index
    @task_types = TaskType.all
  end

  # GET /task_types/1
  # GET /task_types/1.json
  def show
  end

  # GET /task_types/new
  def new
    @task_type = TaskType.new
  end

  # GET /task_types/1/edit
  def edit
  end

  # POST /task_types
  # POST /task_types.json
  def create
    @task_type = TaskType.new(task_type_params)

    respond_to do |format|
      if @task_type.save
        format.html { redirect_to @task_type, notice: 'Task type was successfully created.' }
        format.json { render :show, status: :created, location: @task_type }
      else
        format.html { render :new }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_types/1
  # PATCH/PUT /task_types/1.json
  def update
    respond_to do |format|
      if @task_type.update(task_type_params)
        format.html { redirect_to @task_type, notice: 'Task type was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_type }
      else
        format.html { render :edit }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_types/1
  # DELETE /task_types/1.json
  def destroy
    @task_type.destroy
    respond_to do |format|
      format.html { redirect_to task_types_url, notice: 'Task type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_type
      @task_type = TaskType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_type_params
      params.require(:task_type).permit(:name, :order)
    end
end

app/helpers/task_types_helper.rb
module TaskTypesHelper
end

app/views/task_types/_form.html.erb
<%= simple_form_for(@task_type) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :order %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/task_types/edit.html.erb
<h1>Editing Task Type</h1>

<%= render 'form', task_type: @task_type %>

<br>

<%= link_to 'Show', @task_type, class: 'btn btn-warning btn-sm' %> |
<%= link_to 'Back', task_types_path, class: 'btn btn-warning btn-sm' %>

app/views/task_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Types</h1>

<table style="table table-hover">
  <thead>
    <tr>
      <th>Order</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_types.order(:order).each do |task_type| %>
      <tr>
        <td><%= task_type.name %></td>
        <td><%= task_type.order %></td>
        <td><%= link_to 'Show', task_type, class: 'btn btn-warning btn-sm' %></td>
        <td><%= link_to 'Edit', edit_task_type_path(task_type), class: 'btn btn-warning btn-sm' %></td>
        <td><%= link_to 'Destroy', task_type, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Type', new_task_type_path, class: 'btn btn-primary btn-sm' %>

app/views/task_types/new.html.erb
<h1>New Task Type</h1>

<%= render 'form', task_type: @task_type %>

<br>

<%= link_to 'Back', task_types_path, class: 'btn btn-warning btn-sm' %>

app/views/task_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_type.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= @task_type.order %>
</p>

<br> 

<%= link_to 'Edit', edit_task_type_path(@task_type), class: 'btn btn-warning btn-sm' %> |
<%= link_to 'Back', task_types_path, class: 'btn btn-warning btn-sm' %>