config/routes.rb
Rails.application.routes.draw do
  resources :festivals do
    resources :musicians
  end
  resources :payment_methods
  resources :sales_reports
  resources :vendors
  resources :ticket_categories
  resources :instructions
  resources :assignments
  resources :tasks
  resources :task_types
  resources :instruments
  resources :team_musicians
  resources :accomodations
  resources :addresses
  devise_for :users
  resources :discussions
  resources :flights
  resources :airlines
  resources :sheets
  resources :notebooks
  resources :event_teams
  resources :events
  resources :teams
  resources :locations
  resources :types
  resources :pieces
  resources :performers
  resources :performances
  resources :musicians
  resources :movements
  resources :concerts
  resources :composers
  root to: 'events#index'
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  belongs_to :pad, polymorphic: true
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :set_sheet, only: [:show, :edit, :update, :destroy]

  # GET /sheets
  # GET /sheets.json
  def index
    @sheets = Sheet.all
  end

  # GET /sheets/1
  # GET /sheets/1.json
  def show
  end

  # GET /sheets/new
  def new
    @sheet = Sheet.new
  end

  # GET /sheets/1/edit
  def edit
  end

  # POST /sheets
  # POST /sheets.json
  def create
    @sheet = Sheet.new(sheet_params)

    respond_to do |format|
      if @sheet.save
        format.html { redirect_to @sheet, notice: 'Sheet was successfully created.' }
        format.json { render :show, status: :created, location: @sheet }
      else
        format.html { render :new }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sheets/1
  # PATCH/PUT /sheets/1.json
  def update
    respond_to do |format|
      if @sheet.update(sheet_params)
        format.html { redirect_to @sheet, notice: 'Sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @sheet }
      else
        format.html { render :edit }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sheets/1
  # DELETE /sheets/1.json
  def destroy
    @sheet.destroy
    respond_to do |format|
      format.html { redirect_to sheets_url, notice: 'Sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sheet
      @sheet = Sheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sheet_params
      params.require(:sheet).permit(:note, :pad_id, :pad_type)
    end
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/_form.html.erb
<%= simple_form_for(@sheet) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :note %>
    <%= f.input :pad_id %>
    <%= f.input :pad_type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/sheets/_sheet_fields.html.erb
<div class="nested-fields">
  <%= f.input :note %>

  <%= f.check_box :_destroy %>

  <%= link_to_remove_association "remove note", f, class: 'btn btn-danger btn-sm' %>
</div>

<br> <br>

app/views/sheets/edit.html.erb
<h1>Editing Sheet</h1>

<%= render 'form', sheet: @sheet %>

<br>

<%= link_to 'Show', @sheet, class: 'btn btn-warning btn-sm' %> |
<%= link_to 'Back', sheets_path, class: 'btn btn-warning btn-sm' %>

app/views/sheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Important Notes</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Note</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sheets.each do |sheet| %>
      <tr>
        <td><%= sheet.note %></td>
        <td><%= sheet.pad_type %></td>
        <td><%= sheet.pad_id %></td>
	<td><%= sheet.pad.try(:start).try(:strftime, "%a %b %e %I:%M%p") %></td>
        <td><%= link_to 'Show', sheet, class: 'btn btn-warning btn-sm' %></td>
        <td><%= link_to 'Edit', edit_sheet_path(sheet), class: 'btn btn-warning btn-sm' %></td>
        <td><!%= link_to 'Destroy', sheet, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sheet', new_sheet_path, class: 'btn btn-primary btn-sm' %>

app/views/sheets/new.html.erb
<h1>New Sheet</h1>

<%= render 'form', sheet: @sheet %>

<%= link_to 'Back', sheets_path, class: 'btn btn-warning btn-sm' %>

app/views/sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @sheet.note %>
</p>

<p>
  <strong>Pad:</strong>
  <%= @sheet.pad_id %>
</p>

<p>
  <strong>Pad type:</strong>
  <%= @sheet.pad_type %>
</p>

<%= link_to 'Edit', edit_sheet_path(@sheet), class: 'btn btn-warning btn-sm' %> |
<%= link_to 'Back', sheets_path, class: 'btn btn-warning btn-sm' %>